/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculos.vista;

import alquilervehiculos.controlador.GestionCoche;
import alquilervehiculos.controlador.GestionUsuario;
import alquilervehiculos.modelo.Coche;
import alquilervehiculos.modelo.Moto;
import alquilervehiculos.modelo.Usuario;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonathan_G
 */
public class MdiVehiculos extends javax.swing.JFrame {

    private GestionUsuario gestionUsuario;
    private Usuario usuarioAutenticado;
    private GestionCoche gestionCoche;

    /**
     * Creates new form MdiVehiculos
     */
    public MdiVehiculos() {
        initComponents();

    }

    private void iniciarMenus(boolean estado) {

        mnuCrearVehiculos.setVisible(estado);
        mnuListarCoches.setVisible(estado);
        mnuVehiculos.setVisible(estado);
    }

    private void gestionPersmisosMenus() {

        iniciarMenus(false);
        switch (usuarioAutenticado.getTipoUsuario().getCodigo()) {
            //Administrador
            case "1":
                iniciarMenus(true);
                break;
            //Usuario
            case "2":
                iniciarMenus(false);
                mnuListarCoches.setVisible(true);
                mnuVehiculos.setVisible(true);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jifCoches = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoches = new javax.swing.JTable();
        lblMatricula = new javax.swing.JLabel();
        lblValorAlquiler = new javax.swing.JLabel();
        lblKmCarro = new javax.swing.JLabel();
        lblExtrasCarro = new javax.swing.JLabel();
        lblEstadoCarro = new javax.swing.JLabel();
        txtMatriculaCarro = new javax.swing.JTextField();
        txtValorAlquilerCarro = new javax.swing.JTextField();
        txtKmCarro = new javax.swing.JTextField();
        btnGuardarCoche = new javax.swing.JButton();
        jifMotos = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMotos = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        mnuMenuAlquiler = new javax.swing.JMenu();
        mnuVehiculos = new javax.swing.JMenu();
        mnuCrearVehiculos = new javax.swing.JMenuItem();
        mnuListarVehiculos = new javax.swing.JMenu();
        mnuListarCoches = new javax.swing.JMenuItem();
        jifListarMotos = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 153, 153));

        jifLogin.setTitle("LOGIN");
        jifLogin.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario* :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña* :");

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addComponent(btnIngresar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        desktopPane.add(jifLogin);
        jifLogin.setBounds(170, 80, 460, 310);

        jifCoches.setClosable(true);
        jifCoches.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCoches.setIconifiable(true);
        jifCoches.setMaximizable(true);
        jifCoches.setResizable(true);
        jifCoches.setTitle("Listado de Coches");
        jifCoches.setVisible(false);

        tblCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Extras", "Matricula", "Km", "Estado", "Valor Alquiler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCoches);

        lblMatricula.setText("Matricula* :");

        lblValorAlquiler.setText("Valor Alquiler* : ");

        lblKmCarro.setText("Km* : ");

        lblExtrasCarro.setText("Extras * : ");

        lblEstadoCarro.setText("Estado * : ");

        btnGuardarCoche.setText("Agregar Coche");
        btnGuardarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifCochesLayout = new javax.swing.GroupLayout(jifCoches.getContentPane());
        jifCoches.getContentPane().setLayout(jifCochesLayout);
        jifCochesLayout.setHorizontalGroup(
            jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCochesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCochesLayout.createSequentialGroup()
                        .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jifCochesLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKmCarro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblExtrasCarro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEstadoCarro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblValorAlquiler))
                        .addGap(14, 14, 14)
                        .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorAlquilerCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatriculaCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCochesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifCochesLayout.setVerticalGroup(
            jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifCochesLayout.createSequentialGroup()
                .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifCochesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifCochesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatricula)
                            .addComponent(txtMatriculaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorAlquiler)
                            .addComponent(txtValorAlquilerCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jifCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKmCarro)
                            .addComponent(txtKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExtrasCarro)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstadoCarro)
                        .addGap(35, 35, 35)
                        .addComponent(btnGuardarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        desktopPane.add(jifCoches);
        jifCoches.setBounds(70, 30, 620, 400);

        jifMotos.setClosable(true);
        jifMotos.setIconifiable(true);
        jifMotos.setMaximizable(true);
        jifMotos.setResizable(true);
        jifMotos.setTitle("Lista de Motos");
        jifMotos.setVisible(false);

        tblMotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Casco", "Matricula", "Km", "Estado", "Valor Alquiler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMotos);

        javax.swing.GroupLayout jifMotosLayout = new javax.swing.GroupLayout(jifMotos.getContentPane());
        jifMotos.getContentPane().setLayout(jifMotosLayout);
        jifMotosLayout.setHorizontalGroup(
            jifMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifMotosLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jifMotosLayout.setVerticalGroup(
            jifMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifMotosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktopPane.add(jifMotos);
        jifMotos.setBounds(72, 14, 580, 320);

        mnuMenuAlquiler.setMnemonic('f');
        mnuMenuAlquiler.setText("Archivo");
        mnuMenuAlquiler.setEnabled(false);

        mnuVehiculos.setText("Vehiculos");

        mnuCrearVehiculos.setMnemonic('s');
        mnuCrearVehiculos.setText("Crear Vehiculos");
        mnuCrearVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearVehiculosActionPerformed(evt);
            }
        });
        mnuVehiculos.add(mnuCrearVehiculos);

        mnuListarVehiculos.setText("Listar Vehiculos");

        mnuListarCoches.setText("Listar Coches");
        mnuListarCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarCochesActionPerformed(evt);
            }
        });
        mnuListarVehiculos.add(mnuListarCoches);

        jifListarMotos.setText("Listar Motos");
        jifListarMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jifListarMotosActionPerformed(evt);
            }
        });
        mnuListarVehiculos.add(jifListarMotos);

        mnuVehiculos.add(mnuListarVehiculos);

        mnuMenuAlquiler.add(mnuVehiculos);

        mnuCerrarSesion.setMnemonic('a');
        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuMenuAlquiler.add(mnuCerrarSesion);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mnuMenuAlquiler.add(exitMenuItem);

        menuBar.add(mnuMenuAlquiler);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        if (txtUsuario.getText() == null || txtUsuario.getText().compareTo("") == 0) {

            JOptionPane.showMessageDialog(this, "Debe diligenciar el usuario ", "Datos Faltantes", 2);
        } else if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        } else {
            gestionUsuario = new GestionUsuario();
            //El correo y passwd que se ingreso esta bueno 
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtUsuario.getText());

            if (matcher.find() == true) {

                usuarioAutenticado = gestionUsuario.
                        validarUsuario(txtUsuario.getText(), txtPassword.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this, "El usuario encontrado no existe", "Datos Erroneos", 0);
                } else {
                    gestionCoche = new GestionCoche();

                    JOptionPane.showMessageDialog(this, "Bienvenido " + usuarioAutenticado, "Bienvenido ", 1);
                    mnuMenuAlquiler.setEnabled(true);
                    gestionPersmisosMenus();
                    jifLogin.hide();

                }

            } else {
                JOptionPane.showMessageDialog(this, "El correo no tiene el formato valido", "Datos erroneos", 0);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuCrearVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCrearVehiculosActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed

        mnuMenuAlquiler.setEnabled(false);
        txtUsuario.setText("");
        txtPassword.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        jifLogin.show();
        try {
            jifCoches.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jifMotos.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_mnuCerrarSesionActionPerformed
    private void pintarCoches() {

        DefaultTableModel model = (DefaultTableModel) tblCoches.getModel();
        model.getDataVector().removeAllElements();
        for (Coche coches : gestionCoche.getCoches()) {

            model.addRow(coches.obtenerArregloObjeto());
        }
        tblCoches.setModel(model);
    }

    private void pintarMotos() {

        DefaultTableModel model = (DefaultTableModel) tblMotos.getModel();
        model.getDataVector().removeAllElements();
        for (Moto motos : gestionCoche.getMotos()) {

            model.addRow(motos.obtenerArregloObjeto());
        }
        tblMotos.setModel(model);
    }

    private void mnuListarCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarCochesActionPerformed

        //LLENAR VEHICULOS
        gestionCoche.llenarCoches();

        //LLENAR VEHICULOS
        pintarCoches();
        jifCoches.repaint();
        jifCoches.show();
        //Maximizar el listado de materias  
        if (jifCoches.isIcon()) {

            try {
                jifCoches.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_mnuListarCochesActionPerformed

    private void jifListarMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jifListarMotosActionPerformed

        //LLENAR VEHICULOS
        gestionCoche.llenarMotos();

        //LLENAR VEHICULOS
        pintarMotos();
        jifMotos.repaint();
        jifMotos.show();
        //Maximizar el listado de materias  
        if (jifMotos.isIcon()) {

            try {
                jifMotos.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jifListarMotosActionPerformed

    private void btnGuardarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCocheActionPerformed

        if (txtMatriculaCarro.getText() == null || txtMatriculaCarro.getText().compareTo("") == 0) {

            JOptionPane.showMessageDialog(this, "Debe diligenciar la matricula del carro ", "Datos Faltantes", 2);
        } else if (txtKmCarro.getText() == null || txtKmCarro.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Debe diligenciar  los Kms del carro ", "Datos Faltantes", 2);
        }
        if (txtValorAlquilerCarro.getText() == null || txtValorAlquilerCarro.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Debe diligenciar  los Kms del carro ", "Datos Faltantes", 2);

        } else {
            Coche co = new Coche(true, txtMatriculaCarro.getText(), Integer.parseInt(txtKmCarro.getText()),
                    true, Double.parseDouble(txtValorAlquilerCarro.getText()));
            gestionCoche.getCoches().add(co);
            pintarCoches();

        }


    }//GEN-LAST:event_btnGuardarCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiVehiculos().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCoche;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JInternalFrame jifCoches;
    private javax.swing.JMenuItem jifListarMotos;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JInternalFrame jifMotos;
    private javax.swing.JLabel lblEstadoCarro;
    private javax.swing.JLabel lblExtrasCarro;
    private javax.swing.JLabel lblKmCarro;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblValorAlquiler;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCrearVehiculos;
    private javax.swing.JMenuItem mnuListarCoches;
    private javax.swing.JMenu mnuListarVehiculos;
    private javax.swing.JMenu mnuMenuAlquiler;
    private javax.swing.JMenu mnuVehiculos;
    private javax.swing.JTable tblCoches;
    private javax.swing.JTable tblMotos;
    private javax.swing.JTextField txtKmCarro;
    private javax.swing.JTextField txtMatriculaCarro;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtValorAlquilerCarro;
    // End of variables declaration//GEN-END:variables

}
